name: Consortium for the Improvement in Quality and Productivity in Clinical Research
favicon: null
layout_spectrum: 0.697916396195069
typography_spectrum: 0.09009070158936083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3706325013190508
  lightness: 0.37767978804185987
  saturation: 0.2725209367927164
  rhythmicContrast: 0.620493478840217
purpose: []
